language: php
php:
  - 7.0
  - 7.1
sudo: false
dist: trusty
before_install:
  - composer self-update --no-interaction || true
before_script:
  - composer install --no-interaction --prefer-dist
  - pecl update-channels; pecl install grpc-1.13.0 > /dev/null
script:
  - ./.travis.sh
env:
  matrix:
    - TEST_GROUP=prereq
    - TEST_GROUP=1
matrix:
  fast_finish: true
